version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: compose/local/django/Dockerfile
    command: /start
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.local
    depends_on:
      - db
    networks:
      - magic_beans_network

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.local
    networks:
      - magic_beans_network

volumes:
  postgres_data:

networks:
  magic_beans_network:
    driver: bridge
